name: core
description: Shared utilities and models.
publish_to: none
repository: https://github.com/flutter-news-app-full-source-code/core

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.16.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.26.1
  very_good_analysis: ^10.0.0
